[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 100000
solc_version = "0.8.24"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]


[lint]
level = "off"
unsafe_typecast = "allow"